generatorName: dart-dio-next
outputDir: ./
inputSpec: ./swagger.json
additionalProperties:
  artifactId: mattermost_dart
  serializableModel: "true"
  nullableFields: "true"
  pubAuthor: "tuyen_vuduc"
  pubAuthorEmail: "tuyenvd@newwave.com.vn"
  pubDescription: "MatterMost API Client for Dart"
  pubHomepage: "https://newwave.vn"
  pubLibrary: mattermost_dart
  pubName: mattermost_dart
  pubVersion: 4.0.0
  sortModelPropertiesByRequiredFlag: "true"
  sortParamsByRequiredFlag: "true"